local ns = _G[LOOTAMELO_NAME]
ns.Database = ns.Database or {}

ns.Database.raids = {
	-- "MC",  -- Molten Core
	-- "OL",  -- Onyxia's Lair
	-- "BWL", -- Blackwing Lair
	-- "ZG",  -- Zul'Gurub
	-- "AQ20",-- Ruins of Ahn'Qiraj
	-- "AQ40",-- Temple of Ahn'Qiraj
	-- "Naxx Vanilla", -- Naxxramas
	-- "Kara", -- Karazhan
	-- "Gruul",-- Gruul's Lair
	-- "Mag",  -- Magtheridon's Lair
	-- "SSC",  -- Serpentshrine Cavern
	-- "TK",   -- The Eye
	"The Battle for Mount Hyjal", -- Mount Hyjal
	"Black Temple", -- Black Temple
	-- "ZA",   -- Zul'Aman
	"Sunwell Plateau", -- Sunwell Plateau
	-- "Naxx 10", -- Naxxramas
	-- "Naxx 25", -- Naxxramas
	-- "OS 10",   -- The Obsidian Sanctum
	-- "OS 25",   -- The Obsidian Sanctum
	-- "EoE 10",  -- The Eye of Eternity
	-- "EoE 25",  -- The Eye of Eternity
	-- "Ulduar 10", -- Ulduar
	-- "Ulduar 25", -- Ulduar
	-- "ToC 10",   -- Trial of the Crusader
	-- "ToC 25",   -- Trial of the Crusader
	-- "ICC 10",   -- Icecrown Citadel
	-- "ICC 25",   -- Icecrown Citadel
	-- "RS 10",    -- Ruby Sanctum
	-- "RS 25"     -- Ruby Sanctum
}

-- mappatura per i nomi presi dall'api GetInstanceInfo() che non coincidono con il nome noto del raid
ns.Database.raidNameMap = {
	["The Sunwell"] = "Sunwell Plateau",
	["The Eye"] = "Tempest Keep",
}

ns.Database.items = {
	["The Battle for Mount Hyjal"] = {
		["Rage Winterchill"] = {
			[30871] = { name = "Bracers of Martyrdom", icon = "inv_bracer_13", dropRate = "8.3%" },
			[30870] = { name = "Cuffs of Devastation", icon = "inv_bracer_12", dropRate = "8.3%" },
			[30863] = { name = "Deadly Cuffs", icon = "inv_bracer_09", dropRate = "8.3%" },
			[30868] = { name = "Rejuvenating Bracers", icon = "inv_bracer_08", dropRate = "8.3%" },
			[30864] = { name = "Bracers of the Pathfinder", icon = "inv_bracer_02", dropRate = "8.3%" },
			[30869] = { name = "Howling Wind Bracers", icon = "inv_bracer_03", dropRate = "8.3%" },
			[30873] = { name = "Stillwater Boots", icon = "inv_boots_chain_08", dropRate = "8.3%" },
			[30866] = { name = "Blood-stained Pauldrons", icon = "inv_shoulder_65", dropRate = "8.3%" },
			[30862] = { name = "Blessed Adamantite Bracers", icon = "inv_bracer_19", dropRate = "8.3%" },
			[30861] = { name = "Furious Shackles", icon = "inv_bracer_15", dropRate = "8.3%" },
			[30865] = { name = "Tracker's Blade", icon = "inv_weapon_shortblade_59", dropRate = "8.3%" },
			[30872] = { name = "Chronicle of Dark Secrets", icon = "inv_offhand_hyjal_d_01", dropRate = "8.3%" },
			[32459] = { name = "Time-Phased Phylactery", icon = "inv_potion_19", dropRate = "100%" },
		},
		["Anetheron"] = {
			[30884] = { name = "Hatefury Mantle", icon = "inv_shoulder_68", dropRate = "8.3%" },
			[30888] = { name = "Anetheron's Noose", icon = "inv_belt_03", dropRate = "8.3%" },
			[30885] = { name = "Archbishop's Slippers", icon = "inv_boots_cloth_14", dropRate = "8.3%" },
			[30879] = { name = "Don Alejandro's Money Belt", icon = "inv_belt_26", dropRate = "8.3%" },
			[30886] = { name = "Enchanted Leather Sandals", icon = "inv_boots_wolf", dropRate = "8.3%" },
			[30887] = { name = "Golden Links of Restoration", icon = "inv_chest_mail_04", dropRate = "8.3%" },
			[30880] = { name = "Quickstrider Moccasins", icon = "inv_boots_chain_09", dropRate = "8.3%" },
			[30878] = { name = "Glimmering Steel Mantle", icon = "inv_shoulder_65", dropRate = "8.3%" },
			[30874] = { name = "The Unbreakable Will", icon = "inv_sword_86", dropRate = "8.3%" },
			[30881] = { name = "Blade of Infamy", icon = "inv_sword_85", dropRate = "8.3%" },
			[30883] = { name = "Pillar of Ferocity", icon = "inv_staff_60", dropRate = "8.3%" },
			[30882] = { name = "Bastion of Light", icon = "inv_shield_38", dropRate = "8.3%" },
		},
		["Kaz'rogal"] = {
			[30895] = { name = "Angelista's Sash", icon = "inv_belt_08", dropRate = "8.3%" },
			[30916] = { name = "Leggings of Channeled Elements", icon = "inv_pants_cloth_27", dropRate = "8.3%" },
			[30894] = { name = "Blue Suede Shoes", icon = "inv_boots_cloth_01", dropRate = "8.3%" },
			[30917] = { name = "Razorfury Mantle", icon = "inv_shoulder_67", dropRate = "8.3%" },
			[30914] = { name = "Belt of the Crescent Moon", icon = "inv_belt_22", dropRate = "8.3%" },
			[30891] = { name = "Black Featherlight Boots", icon = "inv_boots_cloth_05", dropRate = "8.3%" },
			[30892] = { name = "Beast-tamer's Shoulders", icon = "inv_shoulder_59", dropRate = "8.3%" },
			[30919] = { name = "Valestalker Girdle", icon = "inv_belt_22", dropRate = "8.3%" },
			[30893] = { name = "Sun-touched Chain Leggings", icon = "inv_pants_mail_17", dropRate = "8.3%" },
			[30915] = { name = "Belt of Seething Fury", icon = "inv_belt_27", dropRate = "8.3%" },
			[30918] = { name = "Hammer of Atonement", icon = "inv_mace_57", dropRate = "8.3%" },
			[30889] = { name = "Kaz'rogal's Hardened Heart", icon = "inv_shield_39", dropRate = "8.3%" },
		},
		["Azgalor"] = {
			[30899] = { name = "Don Rodrigo's Poncho", icon = "inv_chest_leather_01", dropRate = "16.7%" },
			[30898] = { name = "Shady Dealer's Pantaloons", icon = "inv_pants_leather_25", dropRate = "16.7%" },
			[30900] = { name = "Bow-stitched Leggings", icon = "inv_pants_mail_15", dropRate = "16.7%" },
			[30896] = { name = "Glory of the Defender", icon = "inv_chest_plate02", dropRate = "16.7%" },
			[30897] = { name = "Girdle of Hope", icon = "inv_belt_28", dropRate = "16.7%" },
			[30901] = { name = "Boundless Agony", icon = "inv_weapon_shortblade_59", dropRate = "16.7%" },
			[31092] = { name = "Gloves of the Forgotten Conqueror", icon = "inv_gauntlets_27", dropRate = "33.3%" },
			[31094] = { name = "Gloves of the Forgotten Protector", icon = "inv_gauntlets_27", dropRate = "33.3%" },
			[31093] = { name = "Gloves of the Forgotten Vanquisher", icon = "inv_gauntlets_27", dropRate = "33.3%" },
		},
		["Archimonde"] = {
			[30913] = { name = "Robes of Rhonin", icon = "inv_chest_cloth_49", dropRate = "8.3%" },
			[30912] = { name = "Leggings of Eternity", icon = "inv_pants_cloth_14", dropRate = "8.3%" },
			[30905] = { name = "Midnight Chestguard", icon = "inv_chest_plate02", dropRate = "8.3%" },
			[30907] = { name = "Mail of Fevered Pursuit", icon = "inv_chest_chain_17", dropRate = "8.3%" },
			[30904] = { name = "Savior's Grasp", icon = "inv_chest_plate02", dropRate = "8.3%" },
			[30903] = { name = "Legguards of Endless Rage", icon = "inv_pants_plate_21", dropRate = "8.3%" },
			[30911] = { name = "Scepter of Purification", icon = "inv_offhand_draenei_a_01", dropRate = "8.3%" },
			[30910] = { name = "Tempest of Chaos", icon = "inv_sword_90", dropRate = "8.3%" },
			[30902] = { name = "Cataclysm's Edge", icon = "inv_sword_68", dropRate = "8.3%" },
			[30908] = { name = "Apostle of Argus", icon = "inv_staff_54", dropRate = "8.3%" },
			[30909] = { name = "Antonidas's Aegis of Rapt Concentration", icon = "inv_shield_40", dropRate = "8.3%" },
			[30906] = { name = "Bristleblitz Striker", icon = "inv_weapon_bow_30", dropRate = "8.3%" },
		},
	},
	["Black Temple"] = {
		["High Warlord Naj'entus"] = {
			[32239] = { name = "Slippers of the Seacaller", icon = "inv_boots_cloth_16", dropRate = "7.1%" },
			[32240] = { name = "Guise of the Tidal Lurker", icon = "inv_helmet_94", dropRate = "7.1%" },
			[32377] = { name = "Mantle of Darkness", icon = "inv_shoulder_67", dropRate = "7.1%" },
			[32241] = { name = "Helm of Soothing Currents", icon = "inv_helmet_97", dropRate = "7.1%" },
			[32234] = { name = "Fists of Mukoa", icon = "inv_gauntlets_59", dropRate = "7.1%" },
			[32242] = { name = "Boots of Oceanic Fury", icon = "inv_boots_chain_12", dropRate = "7.1%" },
			[32232] = { name = "Eternium Shell Bracers", icon = "inv_bracer_14", dropRate = "7.1%" },
			[32243] = { name = "Pearl Inlaid Boots", icon = "inv_boots_chain_08", dropRate = "7.1%" },
			[32245] = { name = "Tide-stomper's Greaves", icon = "inv_boots_plate_04", dropRate = "7.1%" },
			[32238] = { name = "Ring of Calming Waves", icon = "inv_jewelry_ring_57", dropRate = "7.1%" },
			[32247] = { name = "Ring of Captured Storms", icon = "inv_jewelry_ring_60", dropRate = "7.1%" },
			[32237] = { name = "The Maelstrom's Fury", icon = "inv_weapon_shortblade_58", dropRate = "7.1%" },
			[32236] = { name = "Rising Tide", icon = "inv_axe_56", dropRate = "7.1%" },
			[32248] = { name = "Halberd of Desolation", icon = "inv_weapon_halberd_20", dropRate = "7.1%" },
		},
		["Supremus"] = {
			[32256] = { name = "Waistwrap of Infinity", icon = "inv_belt_03", dropRate = "7.7%" },
			[32252] = { name = "Nether Shadow Tunic", icon = "inv_chest_leather_03", dropRate = "7.7%" },
			[32259] = { name = "Bands of the Coming Storm", icon = "inv_bracer_02", dropRate = "7.7" },
			[32251] = { name = "Wraps of Precise Flight", icon = "inv_bracer_06", dropRate = "7.7%" },
			[32258] = { name = "Naturalist's Preserving Cinch", icon = "inv_belt_22", dropRate = "7.7" },
			[32250] = { name = "Pauldrons of Abyssal Fury", icon = "inv_shoulder_haremmatron_d_01", dropRate = "7.7%" },
			[32260] = { name = "Choker of Endless Nightmares", icon = "inv_jewelry_necklace_35", dropRate = "7.7%" },
			[32261] = { name = "Band of the Abyssal Lord", icon = "inv_jewelry_ring_70", dropRate = "7.7%" },
			[32257] = { name = "Idol of the White Stag", icon = "inv_qirajidol_alabaster", dropRate = "7.7%" },
			[32254] = { name = "The Brutalizer", icon = "inv_axe_59", dropRate = "7.7%" },
			[32262] = { name = "Syphon of the Nathrezim", icon = "inv_mace_44", dropRate = "7.7%" },
			[32255] = { name = "Felstone Bulwark", icon = "inv_shield_38", dropRate = "7.7%" },
			[32253] = { name = "Legionkiller", icon = "inv_weapon_crossbow_20", dropRate = "7.7%" },
		},
		["Shade of Akama"] = {
			[32273] = { name = "Amice of Brilliant Light", icon = "inv_shoulder_63", dropRate = "7.1%" },
			[32270] = { name = "Focused Mana Bindings", icon = "inv_bracer_10", dropRate = "7.1%" },
			[32513] = { name = "Wristbands of Divine Influence", icon = "inv_bracer_13", dropRate = "7.1%" },
			[32265] = { name = "Shadow-walker's Cord", icon = "inv_belt_26", dropRate = "7.1%" },
			[32271] = { name = "Kilt of Immortal Nature", icon = "inv_pants_leather_23", dropRate = "7.1%" },
			[32264] = { name = "Shoulders of the Hidden Predator", icon = "inv_shoulder_59", dropRate = "7.1%" },
			[32275] = { name = "Spiritwalker Gauntlets", icon = "inv_gauntlets_61", dropRate = "7.1%" },
			[32276] = { name = "Flashfire Girdle", icon = "inv_belt_13", dropRate = "7.1%" },
			[32279] = { name = "The Seeker's Wristguards", icon = "inv_bracer_17", dropRate = "7.1%" },
			[32278] = { name = "Grips of Silent Justice", icon = "inv_gauntlets_62", dropRate = "7.1%" },
			[32263] = { name = "Praetorian's Legguards", icon = "inv_pants_plate_07", dropRate = "7.1%" },
			[32268] = { name = "Myrmidon's Treads", icon = "inv_boots_plate_06", dropRate = "7.1%" },
			[32266] = { name = "Ring of Deceitful Intent", icon = "inv_jewelry_ring_68", dropRate = "7.1%" },
			[32361] = { name = "Blind-Seers Icon", icon = "inv_misc_orb_05", dropRate = "7.1%" },
		},
		["Teron Gorefiend"] = {
			[32323] = { name = "Shadowmoon Destroyer's Drape", icon = "inv_misc_cape_naxxramas_02", dropRate = "8.3%" },
			[32329] = { name = "Cowl of Benevolence", icon = "inv_helmet_32", dropRate = "8.3%" },
			[32327] = { name = "Robe of the Shadow Council", icon = "inv_chest_cloth_51", dropRate = "8.3%" },
			[32324] = { name = "Insidious Bands", icon = "inv_bracer_04", dropRate = "8.3%" },
			[32328] = { name = "Botanist's Gloves of Growth", icon = "inv_gauntlets_24", dropRate = "8.3%" },
			[32510] = { name = "Softstep Boots of Tracking", icon = "inv_boots_chain_01", dropRate = "8.3%" },
			[32280] = { name = "Gauntlets of Enforcement", icon = "inv_gauntlets_62", dropRate = "8.3%" },
			[32512] = { name = "Girdle of Lordaeron's Fallen", icon = "inv_belt_28", dropRate = "8.3%" },
			[32330] = {
				name = "Totem of Ancestral Guidance",
				icon = "spell_nature_giftofthewaterspirit",
				dropRate = "8.3%",
			},
			[32348] = { name = "Soul Cleaver", icon = "inv_axe_60", dropRate = "8.3%" },
			[32326] = { name = "Twisted Blades of Zarak", icon = "inv_throwingknife_04", dropRate = "8.3%" },
			[32325] = { name = "Rifle of the Stoic Guardian", icon = "inv_weapon_rifle_21", dropRate = "8.3%" },
		},
		["Gurtogg Bloodboil"] = {
			[32337] = { name = "Shroud of Forgiveness", icon = "inv_misc_cape_13", dropRate = "7.7%" },
			[32338] = { name = "Blood-cursed Shoulderpads", icon = "inv_shoulder_02", dropRate = "7.7%" },
			[32340] = { name = "Garments of Temperance", icon = "inv_chest_cloth_35", dropRate = "7.7%" },
			[32339] = { name = "Belt of Primal Majesty", icon = "inv_belt_24", dropRate = "7.7%" },
			[32334] = { name = "Vest of Mounting Assault", icon = "inv_chest_samurai", dropRate = "7.7%" },
			[32342] = { name = "Girdle of Mighty Resolve", icon = "inv_belt_27", dropRate = "7.7%" },
			[32333] = { name = "Girdle of Stability", icon = "inv_belt_33", dropRate = "7.7%" },
			[32341] = { name = "Leggings of Divine Retribution", icon = "inv_pants_plate_20", dropRate = "7.7%" },
			[32335] = { name = "Unstoppable Aggressor's Ring", icon = "inv_jewelry_ring_71", dropRate = "7.7%" },
			[32501] = {
				name = "Shadowmoon Insignia",
				icon = "inv_jewelcrafting_shadowsongamethyst_01",
				dropRate = "7.7%",
			},
			[32269] = { name = "Messenger of Fate", icon = "inv_weapon_shortblade_63", dropRate = "7.7%" },
			[32344] = { name = "Staff of Immaculate Recovery", icon = "inv_staff_61", dropRate = "7.7%" },
			[32343] = { name = "Wand of Prismatic Focus", icon = "inv_wand_16", dropRate = "7.7%" },
		},
		["Reliquary of Souls"] = {
			[32353] = { name = "Gloves of Unfailing Faith", icon = "inv_gauntlets_63", dropRate = "7.7%" },
			[32351] = { name = "Elunite Empowered Bracers", icon = "inv_bracer_09", dropRate = "7.7%" },
			[32347] = { name = "Grips of Damnation", icon = "inv_gauntlets_65", dropRate = "7.7%" },
			[32352] = { name = "Naturewarden's Treads", icon = "inv_boots_08", dropRate = "7.7%" },
			[32517] = { name = "The Wavemender's Mantle", icon = "inv_shoulder_61", dropRate = "7.7%" },
			[32346] = { name = "Boneweave Girdle", icon = "inv_belt_14", dropRate = "7.7%" },
			[32354] = { name = "Crown of Empowered Fate", icon = "inv_helmet_96", dropRate = "7.7%" },
			[32345] = { name = "Dreadboots of the Legion", icon = "inv_boots_plate_02", dropRate = "7.7%" },
			[32349] = { name = "Translucent Spellthread Necklace", icon = "inv_jewelry_necklace_30", dropRate = "7.7%" },
			[32362] = { name = "Pendant of Titans", icon = "inv_jewelry_amulet_03", dropRate = "7.7%" },
			[32350] = { name = "Touch of Inspiration", icon = "inv_misc_gem_ebondraenite_02", dropRate = "7.7%" },
			[32332] = { name = "Torch of the Damned", icon = "inv_mace_49", dropRate = "7.7%" },
			[32363] = { name = "Naaru-Blessed Life Rod", icon = "inv_wand_15", dropRate = "7.7%" },
		},
		["Mother Shahraz"] = {
			[32367] = { name = "Leggings of Devastation", icon = "inv_pants_cloth_15", dropRate = "16.7%" },
			[32366] = { name = "Shadowmaster's Boots", icon = "inv_boots_cloth_02", dropRate = "16.7%" },
			[32365] = { name = "Heartshatter Breastplate", icon = "inv_chest_plate08", dropRate = "16.7%" },
			[32370] = { name = "Nadina's Pendant of Purity", icon = "inv_jewelry_necklace_32", dropRate = "16.7%" },
			[32368] = { name = "Tome of the Lightbringer", icon = "inv_relics_libramofhope", dropRate = "16.7%" },
			[32369] = { name = "Blade of Savagery", icon = "inv_sword_87", dropRate = "16.7%" },
			[31101] = { name = "Pauldrons of the Forgotten Conqueror", icon = "inv_shoulder_22", dropRate = "33.3%" },
			[31103] = { name = "Pauldrons of the Forgotten Protector", icon = "inv_shoulder_22", dropRate = "33.3%" },
			[31102] = { name = "Pauldrons of the Forgotten Vanquisher", icon = "inv_shoulder_22", dropRate = "33.3%" },
		},
		["Gathios the Shatterer"] = {
			[31098] = { name = "Leggings of the Forgotten Conqueror", icon = "inv_pants_plate_17", dropRate = "33.3%" },
			[31100] = { name = "Leggings of the Forgotten Protector", icon = "inv_pants_plate_17", dropRate = "33.3%" },
			[31099] = { name = "Leggings of the Forgotten Vanquisher", icon = "inv_pants_plate_17", dropRate = "33.3%" },
		},
		["High Nethermancer Zerevor"] = {
			[31098] = { name = "Leggings of the Forgotten Conqueror", icon = "inv_pants_plate_17", dropRate = "33.3%" },
			[31100] = { name = "Leggings of the Forgotten Protector", icon = "inv_pants_plate_17", dropRate = "33.3%" },
			[31099] = { name = "Leggings of the Forgotten Vanquisher", icon = "inv_pants_plate_17", dropRate = "33.3%" },
			[32519] = { name = "Belt of Divine Guidance", icon = "inv_belt_07", dropRate = "16.7%" },
			[32331] = { name = "Cloak of the Illidari Council", icon = "inv_misc_cape_20", dropRate = "16.7%" },
			[32518] = { name = "Veil of Turning Leaves", icon = "inv_shoulder_58", dropRate = "16.7%" },
			[32376] = { name = "Forest Prowler's Helm", icon = "inv_helmet_95", dropRate = "16.7%" },
			[32373] = { name = "Helm of the Illidari Shatterer", icon = "inv_helmet_98", dropRate = "16.7%" },
			[32505] = { name = "Madness of the Betrayer", icon = "spell_shadow_charm", dropRate = "16.7%" },
		},
		["Veras Darkshadow"] = {
			[31098] = { name = "Leggings of the Forgotten Conqueror", icon = "inv_pants_plate_17", dropRate = "33.3%" },
			[31100] = { name = "Leggings of the Forgotten Protector", icon = "inv_pants_plate_17", dropRate = "33.3%" },
			[31099] = { name = "Leggings of the Forgotten Vanquisher", icon = "inv_pants_plate_17", dropRate = "33.3%" },
		},
		["Illidan Stormrage"] = {
			[32524] = { name = "Shroud of the Highborne", icon = "inv_misc_cape_06", dropRate = "8.3%" },
			[32525] = { name = "Cowl of the Illidari High Lord", icon = "inv_helmet_53", dropRate = "8.3%" },
			[32235] = { name = "Cursed Vision of Sargeras", icon = "inv_misc_bandana_03", dropRate = "8.3%" },
			[32521] = { name = "Faceplate of the Impenetrable", icon = "inv_helmet_98", dropRate = "8.3%" },
			[32497] = { name = "Stormrage Signet Ring", icon = "inv_jewelry_ring_67", dropRate = "8.3%" },
			[32483] = { name = "The Skull of Gul'dan", icon = "inv_misc_bone_elfskull_01", dropRate = "8.3%" },
			[32496] = { name = "Memento of Tyrande", icon = "inv_summerfest_fireflower", dropRate = "8.3%" },
			[32837] = { name = "Warglaive of Azzinoth", icon = "inv_weapon_glave_01", dropRate = "5%" },
			[32838] = { name = "Warglaive of Azzinoth", icon = "inv_weapon_glave_01", dropRate = "5%" },
			[31089] = {
				name = "Chestguard of the Forgotten Conqueror",
				icon = "inv_chest_chain_03",
				dropRate = "33.3%",
			},
			[31091] = {
				name = "Chestguard of the Forgotten Protector",
				icon = "inv_chest_chain_03",
				dropRate = "33.3%",
			},
			[31090] = {
				name = "Chestguard of the Forgotten Vanquisher",
				icon = "inv_chest_chain_03",
				dropRate = "33.3%",
			},
			[32471] = { name = "Shard of Azzinoth", icon = "inv_weapon_shortblade_62", dropRate = "8.3%" },
			[32500] = { name = "Crystal Spire of Karabor", icon = "inv_mace_56", dropRate = "8.3%" },
			[32374] = { name = "Zhar'doom, Greatstaff of the Devourer", icon = "inv_staff_59", dropRate = "8.3%" },
			[32375] = { name = "Bulwark of Azzinoth", icon = "inv_shield_32", dropRate = "8.3%" },
			[32336] = { name = "Black Bow of the Betrayer", icon = "inv_weapon_bow_31", dropRate = "8.3%" },
		},
	},
	["Sunwell Plateau"] = {
		["Kalecgos"] = {
			[34170] = { name = "Pantaloons of Calming Strife", icon = "inv_pants_cloth_07", dropRate = "14.3%" },
			[34169] = { name = "Breeches of Natural Aggression", icon = "inv_pants_leather_23", dropRate = "14.3%" },
			[34168] = { name = "Starstalker Legguards", icon = "inv_pants_mail_16", dropRate = "14.3%" },
			[34167] = { name = "Legplates of the Holy Juggernaut", icon = "inv_pants_plate_22", dropRate = "14.3%" },
			[34166] = { name = "Band of Lucent Beams", icon = "inv_jewelry_ring_57", dropRate = "14.3%" },
			[34165] = { name = "Fang of Kalecgos", icon = "inv_weapon_shortblade_74", dropRate = "14.3%" },
			[34164] = { name = "Dragonscale-Encrusted Longblade", icon = "inv_sword_115", dropRate = "14.3%" },
			[34848] = { name = "Bracers of the Forgotten Conqueror", icon = "inv_bracer_16", dropRate = "33.3%" },
			[34851] = { name = "Bracers of the Forgotten Protector", icon = "inv_bracer_17", dropRate = "33.3%" },
			[34852] = { name = "Bracers of the Forgotten Vanquisher", icon = "inv_bracer_15", dropRate = "33.3%" },
		},
		["Brutallus"] = {
			[34181] = { name = "Leggings of Calamity", icon = "inv_pants_cloth_05", dropRate = "16.7%" },
			[34180] = { name = "Felfury Legplates", icon = "inv_pants_plate_24", dropRate = "16.7%" },
			[34178] = { name = "Collar of the Pit Lord", icon = "inv_jewelry_necklace_47", dropRate = "16.7%" },
			[34177] = { name = "Clutch of Demise", icon = "inv_jewelry_necklace_43", dropRate = "16.7%" },
			[34179] = { name = "Heart of the Pit", icon = "inv_offhand_sunwell_d_02", dropRate = "16.7%" },
			[34176] = { name = "Reign of Misery", icon = "inv_mace_73", dropRate = "16.7%%" },
			[34853] = { name = "Belt of the Forgotten Conqueror", icon = "inv_belt_31", dropRate = "33.3%" },
			[34854] = { name = "Belt of the Forgotten Protector", icon = "inv_belt_33", dropRate = "33.3%" },
			[34855] = { name = "Belt of the Forgotten Vanquisher", icon = "inv_belt_27", dropRate = "33.3%" },
		},
		["Felmyst"] = {
			[34352] = { name = "Borderland Fortress Grips", icon = "inv_gauntlets_68", dropRate = "16.7%" },
			[34188] = { name = "Leggings of the Immortal Night", icon = "inv_pants_leather_27", dropRate = "16.7%" },
			[34186] = { name = "Chain Links of the Tumultuous Storm", icon = "inv_pants_mail_15", dropRate = "16.7%" },
			[34184] = { name = "Brooch of the Highborne", icon = "inv_jewelry_necklace_44", dropRate = "16.7%" },
			[34185] = { name = "Sword Breaker's Bulwark", icon = "inv_shield_53", dropRate = "16.7%" },
			[34182] = { name = "Grand Magister's Staff of Torrents", icon = "inv_staff_74", dropRate = "16.7%" },
			[34856] = { name = "Boots of the Forgotten Conqueror", icon = "inv_boots_plate_06", dropRate = "33.3%" },
			[34857] = { name = "Boots of the Forgotten Protector", icon = "inv_boots_plate_04", dropRate = "33.3%" },
			[34858] = { name = "Boots of the Forgotten Vanquisher", icon = "inv_boots_plate_07", dropRate = "33.3%" },
		},
		["Eredar Twins"] = {
			[34205] = { name = "Shroud of Redeemed Souls", icon = "inv_misc_cape_06", dropRate = "5.5%" },
			[34190] = { name = "Crimson Paragon's Cover", icon = "inv_misc_cape_18", dropRate = "5.5%" },
			[3425.5] = { name = "Amice of the Convoker", icon = "inv_shoulder_96", dropRate = "5.5%" },
			[34202] = { name = "Shawl of Wonderment", icon = "inv_shoulder_96", dropRate = "5.5%" },
			[34209] = { name = "Spaulders of Reclamation", icon = "inv_shoulder_88", dropRate = "5.5%" },
			[34195] = { name = "Shoulderpads of Vehemence", icon = "inv_shoulder_88", dropRate = "5.5%" },
			[34194] = { name = "Mantle of the Golden Forest", icon = "inv_shoulder_90", dropRate = "5.5%" },
			[34208] = { name = "Equilibrium Epaulets", icon = "inv_shoulder_90", dropRate = "5.5%" },
			[34192] = { name = "Pauldrons of Perseverance", icon = "inv_shoulder_89", dropRate = "5.5%" },
			[34193] = { name = "Spaulders of the Thalassian Savior", icon = "inv_shoulder_89", dropRate = "5.5%" },
			[35290] = { name = "Sin'dorei Pendant of Conquest", icon = "inv_jewelry_necklace_36", dropRate = "33.3" },
			[35291] = { name = "Sin'dorei Pendant of Salvation", icon = "inv_jewelry_necklace_36", dropRate = "33.3" },
			[35292] = { name = "Sin'dorei Pendant of Triumph", icon = "inv_jewelry_necklace_36", dropRate = "33.3" },
			[34204] = { name = "Amulet of Unfettered Magics", icon = "inv_jewelry_necklace_40", dropRate = "5.5%" },
			[34189] = { name = "Band of Ruinous Delight", icon = "inv_jewelry_ring_36", dropRate = "5.5%" },
			[34206] = { name = "Book of Highborne Hymns", icon = "inv_offhand_sunwell_d_01", dropRate = "5.5%" },
			[34197] = { name = "Shiv of Exsanguination", icon = "inv_weapon_shortblade_75", dropRate = "5.5%" },
			[34199] = { name = "Archon's Gavel", icon = "inv_mace_71", dropRate = "5.5%" },
			[34203] = { name = "Grip of Mannoroth", icon = "inv_weapon_hand_15", dropRate = "5.5%" },
			[34198] = { name = "Stanchion of Primal Instinct", icon = "inv_staff_12", dropRate = "5.5%" },
			[34196] = { name = "Golden Bow of Quel'Thalas", icon = "inv_weapon_bow_38", dropRate = "5.5%" },
			[34848] = { name = "Bracers of the Forgotten Conqueror", icon = "inv_bracer_16", dropRate = "11.1%" },
			[34851] = { name = "Bracers of the Forgotten Protector", icon = "inv_bracer_17", dropRate = "11.1%" },
			[34852] = { name = "Bracers of the Forgotten Vanquisher", icon = "inv_bracer_15", dropRate = "11.1%" },
			[34853] = { name = "Belt of the Forgotten Conqueror", icon = "inv_belt_31", dropRate = "11.1%" },
			[34854] = { name = "Belt of the Forgotten Protector", icon = "inv_belt_33", dropRate = "11.1%" },
			[34855] = { name = "Belt of the Forgotten Vanquisher", icon = "inv_belt_27", dropRate = "11.1%" },
			[34856] = { name = "Boots of the Forgotten Conqueror", icon = "inv_boots_plate_06", dropRate = "11.1%" },
			[34857] = { name = "Boots of the Forgotten Protector", icon = "inv_boots_plate_04", dropRate = "11.1%" },
			[34858] = { name = "Boots of the Forgotten Vanquisher", icon = "inv_boots_plate_07", dropRate = "11.1%" },
		},
		["M'uru"] = {
			[34232] = { name = "Fel Conquerer Raiments", icon = "inv_chest_cloth_51", dropRate = "5.6%" },
			[34233] = { name = "Robes of Faltered Light", icon = "inv_chest_cloth_32", dropRate = "5.6%" },
			[34212] = { name = "Sunglow Vest", icon = "inv_chest_leather_12", dropRate = "5.6%" },
			[34211] = { name = "Harness of Carnal Instinct", icon = "inv_chest_leather_14", dropRate = "5.6%" },
			[34234] = { name = "Shadowed Gauntlets of Paroxysm", icon = "inv_gauntlets_28", dropRate = "5.6%" },
			[34229] = { name = "Garments of Serene Shores", icon = "inv_chest_chain_11", dropRate = "5.6%" },
			[34228] = { name = "Vicious Hawkstrider Hauberk", icon = "inv_chest_chain_17", dropRate = "5.6%" },
			[34215] = { name = "Warharness of Reckless Fury", icon = "inv_chest_plate20", dropRate = "5.6%" },
			[34240] = { name = "Gauntlets of the Soothed Soul", icon = "inv_gauntlets_20", dropRate = "5.6%" },
			[34216] = { name = "Heroic Judicator's Chestguard", icon = "inv_chest_plate18", dropRate = "5.6%" },
			[34213] = { name = "Ring of Hardened Resolve", icon = "inv_jewelry_ring_72", dropRate = "5.6%" },
			[34230] = { name = "Ring of Omnipotence", icon = "inv_jewelry_ring_68", dropRate = "5.6%" },
			[35282] = { name = "Sin'dorei Band of Dominance", icon = "inv_jewelry_ring_60", dropRate = "33.3%" },
			[35283] = { name = "Sin'dorei Band of Salvation", icon = "inv_jewelry_ring_60", dropRate = "33.3%" },
			[35284] = { name = "Sin'dorei Band of Triumph", icon = "inv_jewelry_ring_60", dropRate = "33.3%" },
			[34427] = { name = "Blackened Naaru Sliver", icon = "inv_jewelry_talisman_16", dropRate = "5.6%" },
			[34430] = { name = "Glimmering Naaru Sliver", icon = "inv_jewelry_talisman_17", dropRate = "5.6%" },
			[34429] = { name = "Shifting Naaru Sliver", icon = "inv_jewelry_talisman_15", dropRate = "5.6%" },
			[34428] = { name = "Steely Naaru Sliver", icon = "inv_jewelry_talisman_18", dropRate = "5.6%" },
			[34214] = { name = "Muramasa", icon = "inv_sword_114", dropRate = "5.6%" },
			[34231] = { name = "Aegis of Angelic Fortune", icon = "inv_shield_52", dropRate = "5.6%" },
		},
		["Kil'jaeden"] = {
			[34241] = { name = "Cloak of Unforgivable Sin", icon = "inv_misc_cape_naxxramas_02", dropRate = "7.1%" },
			[34242] = { name = "Tattered Cape of Antonidas", icon = "inv_misc_cape_20", dropRate = "7.1%" },
			[34339] = { name = "Cowl of Light's Purity", icon = "inv_helmet_132", dropRate = "7.1%" },
			[34340] = { name = "Dark Conjuror's Collar", icon = "inv_helmet_132", dropRate = "7.1%%" },
			[34342] = { name = "Handguards of the Dawn", icon = "inv_gauntlets_16", dropRate = "7.1%" },
			[34344] = { name = "Handguards of Defiled Worlds", icon = "inv_gauntlets_15", dropRate = "7.1%%" },
			[34244] = { name = "Duplicitous Guise", icon = "inv_helmet_126", dropRate = "7.1%" },
			[34245] = { name = "Cover of Ursol the Wise", icon = "inv_helmet_126", dropRate = "7.1%" },
			[34333] = { name = "Coif of Alleria", icon = "inv_helmet128", dropRate = "7.1%" },
			[34332] = { name = "Cowl of Gul'dan", icon = "inv_helmet128", dropRate = "7.1%" },
			[34343] = { name = "Thalassian Ranger Gauntlets", icon = "inv_gauntlets_51", dropRate = "7.1%" },
			[34243] = { name = "Helm of Burning Righteousness", icon = "inv_helmet_25", dropRate = "7.1%%" },
			[34345] = { name = "Crown of Anasterian", icon = "inv_helmet_92", dropRate = "7.1%" },
			[34341] = { name = "Borderland Paingrips", icon = "inv_gauntlets_65", dropRate = "7.1%" },
			[34334] = { name = "Thori'dal, the Stars' Fury", icon = "inv_weapon_bow_39", dropRate = "6%" },
			[34329] = { name = "Crux of the Apocalypse", icon = "inv_weapon_shortblade_75", dropRate = "16.7%" },
			[34247] = { name = "Apolyon, the Soul-Render", icon = "inv_sword_116", dropRate = "16.7%" },
			[34335] = { name = "Hammer of Sanctification", icon = "inv_mace_72", dropRate = "16.7%%" },
			[34331] = { name = "Hand of the Deceiver", icon = "inv_weapon_hand_15", dropRate = "16.7%" },
			[34336] = { name = "Sunflare", icon = "inv_weapon_shortblade_73", dropRate = "16.7%" },
			[34337] = { name = "Golden Staff of the Sin'dorei", icon = "inv_staff_73", dropRate = "16.7%" },
		},
	},
}
